module.exports.Assureur = require('./Assureur')
module.exports.Category = require('./Categorie')
module.exports.Quote = require('./Quotes')
module.exports.Garanty = require('./Garantie')
module.exports.Poste = require('./Poste')
module.exports.Commentaire = require('./Commentaire')